GET http://localhost:8080/user/1/bill
Accept: application/json
Content-Type: application/json

###
POST http://localhost:8080/user/1/projects/1/paymentplan/1/1
Accept: application/json
Content-Type: application/json

{
  "buyDate": "2020-25-17",
  "billingAddress": "",
  "country": "Chile",
  "city": "Santiago"
}
###
