###
GET http://localhost:8080/paymentPlan
Accept: application/json

###
GET http://localhost:8080/paymentPlan/1
Accept: application/json

###
POST http://localhost:8080/paymentPlan
Accept: application/json
Content-Type: application/json

{
  "plan": "12 meses",
  "description": "12 meses de publicidad para tu proyecto",
  "cost": 2500,
  "duration": 12
}
###
